services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./client/dist:/usr/share/nginx/html
    ports:
      - "81:80"
  backend:
    build: ./server
    ports:
      - "82:5000"
    environment:
      - MONGODB_URI=mongodb+srv://navodyatheshan4_db_user:ZOId7jbikOuGU6PN@toystore.dixr9mo.mongodb.net/?appName=toystore
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017"